/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  community: [
    // {
    //   type: 'autogenerated',
    //   dirName: '.',
    // },
    { type: 'doc', id: 'best-practices' },
    { type: 'doc', id: 'cadence-vs-temporal' },
    { type: 'doc', id: 'how-to-add-a-new-faq' },
  ],
};
